# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/arireitman/CLionProjects/OpenGLLearning/includes/glm/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/arireitman/CLionProjects/OpenGLLearning/includes/glm/glm/CMakeLists.txt))

/Users/arireitman/CLionProjects/OpenGLLearning/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/Cellar/cmake/3.25.2/bin/cmake -H/Users/arireitman/CLionProjects/OpenGLLearning -B/Users/arireitman/CLionProjects/OpenGLLearning
